# port: 3000

services:
  currencia:
    image: ghcr.io/hugorcd/currencia:latest
    container_name: currencia
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NUXT_OAUTH_GITHUB_CLIENT_ID=${NUXT_OAUTH_GITHUB_CLIENT_ID}
      - NUXT_OAUTH_GITHUB_CLIENT_SECRET=${NUXT_OAUTH_GITHUB_CLIENT_SECRET}
      - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}
      - NUXT_PRIVATE_RESEND_API_KEY=${NUXT_PRIVATE_RESEND_API_KEY}
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/api/hello" ]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
  prisma_migrate:
    image: ghcr.io/hugorcd/currencia:latest
    container_name: prisma_migrate
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:postgres@currencia_db:5432/postgres}
    command: bunx prisma migrate deploy --schema ./prisma/schema.prisma
    restart: no
    networks:
      - currencia-network

networks:
  currencia-network:
    driver: bridge
